language: objective-c
osx_image: xcode8.1
before_install: 
  - cd Projects
  - brew update
  - brew install carthage
  - carthage bootstrap --verbose

env:
  - >
    xcode_workspace=Akane.xcworkspace
    xcode_scheme=AkaneCore
    xcode_sdk=iphonesimulator
    xcode_platform="platform=iOS Simulator,name=iPhone 6"

install: cd Projects/ pod install

script:
  - >
    set -o pipefail && xcodebuild
    -workspace ${xcode_workspace}
    -scheme ${xcode_scheme}
    -sdk ${xcode_sdk}
    -destination "${xcode_platform}" test | xcpretty -c

branches:
  except:
    - /^tags.+/
